__title__ = 'pynoco'
__package_name__ = 'pynoco'
__version__ = '1.0.0'
__description__ = 'A Python client for NocoDB, The Open Source Airtable Alternative.'
__email__ = 'talaat049@gmail.com'
__author__ = 'Talaat Hasanin'
__github__ = 'https://github.com/TalaatHasanin/nocodb-python-client'
__copyright__ = 'Copyright 2024-Talaat Hasanin'
